.TH "Git2Graphviz.h" 3 "Sun May 31 2020" "Version 1.0" "Git2Graphviz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Git2Graphviz.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGit2Graphviz\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGIT2GRAPHVIZ_VERSION\fP   1\&.0"
.br
.RI "Program Version\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GIT2GRAPHVIZ_VERSION   1\&.0"

.PP
Program Version\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Git2Graphviz from the source code\&.
