.TH "Git2Graphviz.cpp" 3 "Sun May 31 2020" "Version 1.0" "Git2Graphviz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Git2Graphviz.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'git2\&.h'\fP
.br
\fC#include 'boost/graph/adjacency_list\&.hpp'\fP
.br
\fC#include 'boost/graph/graphviz\&.hpp'\fP
.br
\fC#include 'Git2Graphviz\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Git2Graphviz from the source code\&.
